### ISSUE TITLE
Unable to use ion-icons

### ISSUE THREAD

**Issue by abhemanyus** [BConquest/hephaestus#2]
I tried to use this theme for my portfolio, but the ion-icons don't work properly.

This is the error message from the browser's console logs:
[ionicons] Deprecated script, please remove: <script src="/livereload.js?port=1024&amp;mindelay=10"></script>
To improve performance it is recommended to set the differential scripts in the head as follows:
<script type="module" src="http://127.0.0.1:1111/ionicons/ionicons.esm.js"></script>
<script nomodule="" src="http://127.0.0.1:1111/ionicons/ionicons.js"></script> ionicons.js:28:11
GEThttp://127.0.0.1:1111/ionicons/ionicons.esm.js
[HTTP/1.1 404 Not Found 2ms]

Loading module from “http://127.0.0.1:1111/ionicons/ionicons.esm.js” was blocked because of a disallowed MIME type (“text/html”). 127.0.0.1:1111
GEThttp://127.0.0.1:1111/favicon.png
[HTTP/1.1 404 Not Found 0ms]

Loading failed for the module with source “http://127.0.0.1:1111/ionicons/ionicons.esm.js”. 127.0.0.1:1111:1:1

This is the code repository: https://github.com/abhemanyus/abhemanyus.github.io

How can I fix this issue?

**Comment by BConquest** [comment]
Hey, I have made some changes to the code with if it is using bundled assests or not. It also should fix the issue that was popping up for you could you pull the code and try it again.

**Comment by abhemanyus** [comment]
Thanks, the icons are working now. They aren't aligned with the text, however.

**Comment by BConquest** [comment]
Hey, icons should be aligned with the text now. Can you checkout the newest changes.

**Comment by abhemanyus** [comment]
I don't see any new changes, have you updated the main branch yet?

**Comment by BConquest** [comment]
Sorry it should be updated now.

**Comment by abhemanyus** [comment]
Looks good, thanks a lot for all your help!
